#!/usr/bin/env bash
set -euo pipefail

export SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/test/core.sh"

cheat::find \
  | grep -q "docker.cheat" \
  && test::success \
  || test::fail
