#!/usr/bin/env bash
set -euo pipefail

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${NAVI_HOME}/test/core.sh"

tests="$(find "$NAVI_HOME/test" -iname "${1:-}*_test.sh")"

for test in $tests; do
   source "$test"
done

test::finish
