#!/usr/bin/env bash
set -euo pipefail

export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

source "${DIR}/src/arg.sh"
source "${DIR}/src/cheat.sh"
source "${DIR}/src/docs.sh"
source "${DIR}/src/misc.sh"
source "${DIR}/src/selection.sh"
source "${DIR}/src/str.sh"
source "${DIR}/src/ui.sh"

source "${DIR}/src/main.sh"

##? Command cheatsheet tool
##?
##? Usage:
##?     cheats [options]
##?
##? Options:
##?     --print                               Prevent script execution [default: false]
##?     --no-interpolation                    Prevent argument interpolation [default: false]
##?     -c --cheat-folder <cheat-folder>      Folder with cheatsheets

docs::eval "$@"

main "$@"
