#!/usr/bin/env bash

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${NAVI_HOME}/tests/core.bash"

TEST_CHEAT_PATH="${NAVI_HOME}/tests/cheats"

_navi() {
   local -r navi="./target/debug/navi"
   NAVI_PATH="$TEST_CHEAT_PATH" "$navi" --fzf-overrides '--no-reverse' best "$1" 2> /dev/null \
      | test::equals "$2"
}

_get_tests() {
   cat "${TEST_CHEAT_PATH}/cases.cheat" \
      | grep '#' \
      | grep ' ->' \
      | sed 's/\\n/ /g' \
      | sed -E 's/# (.*) -> "(.*)"/\1|\2/g'
}

if ! command_exists fzf; then
   apt install fzf \
      || sudo apt install fzf \
      || (git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && yes | ~/.fzf/install) \
      || true
fi

source ~/.bashrc || true

cd "$NAVI_HOME"

test::set_suite "cases"
IFS=$'\n'
for i in $(_get_tests); do
   query="$(echo "$i" | cut -d'|' -f1)"
   expected="$(echo "$i" | cut -d'|' -f2)"
   test::run "$query" _navi "$query" "$expected"
done

exit $FAILED
