#!/usr/bin/env bash

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${NAVI_HOME}/tests/core.bash"

TEST_CHEAT_PATH="${NAVI_HOME}/tests/cheats"

_navi() {
   local -r navi="./target/debug/navi"
   RUST_BACKTRACE=1 NAVI_PATH="$TEST_CHEAT_PATH" "$navi" --fzf-overrides '--no-reverse' best "$1"
}

_navi_test() {
   _navi "$1" 2> /dev/null \
      | test::equals "$2"
}

_get_tests() {
   cat "${TEST_CHEAT_PATH}/cases.cheat" \
      | grep '#' \
      | grep ' ->' \
      | sed 's/\\n/ /g' \
      | sed -E 's/# (.*) -> "(.*)"/\1|\2/g'
}

cd "$NAVI_HOME"

which fzf

# TODO: remove
_navi trivial "foo"

test::set_suite "cases"
IFS=$'\n'
for i in $(_get_tests); do
   query="$(echo "$i" | cut -d'|' -f1)"
   expected="$(echo "$i" | cut -d'|' -f2)"
   test::run "$query" _navi_test "$query" "$expected"
done

exit $FAILED
