#!/usr/bin/env bash
set -euo pipefail

##? action release

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${NAVI_HOME}/scripts/install"

is_windows() {
  local -r target="$1"
  echo "$target" | grep -q "windows" 
}

get_env_target() {
   eval $(rustc --print cfg | grep target)
   echo "${target_arch}-${target_vendor}-${target_os}-${target_env}"
}

as_cross_target() {
   sed "s/osx/apple-darwin/g"
}

release() {
   target="${1:-}"
   local -r cross_target="$(as_cross_target "$target")"

   TAR_DIR="${NAVI_HOME}/target/tar"
   local use_zip=false
   local cross=true

   local -r env_target="$(get_env_target)"

   if [[ $target == *"osx"* ]]; then
      cross=false
      if ! [[ "$OSTYPE" == "darwin"* ]]; then
         echoerr "OSTYPE=${OSTYPE}. OSX cross-compile isn't allowed"
         exit 1
      fi
   elif [[ $target == $env_target ]]; then
      cross=false
   fi

   cd "$NAVI_HOME"

   rm -rf "${NAVI_HOME}/target" 2> /dev/null || true

   if $cross; then
      cargo install cross 2> /dev/null || true
      cross build --release --locked --target "$cross_target"
      local -r bin_folder="${cross_target}/release"
   else
      cargo build --release --locked
      local -r bin_folder="release"
   fi

   _ls "${bin_folder}"

   if is_windows "$target"; then
      local -r exe_ext=".exe"
      use_zip=true
   else
      local -r exe_ext=""
   fi

   bin_path="${NAVI_HOME}/target/${bin_folder}/navi${exe_ext}"

   chmod +x "$bin_path"
   mkdir -p "$TAR_DIR" 2> /dev/null || true

   cp "$bin_path" "$TAR_DIR"

   cd "$TAR_DIR"
   
   if $use_zip; then
      zip -r navi.zip *
      echo ::set-output name=EXTENSION::zip
   else 
      tar -czf navi.tar.gz *
      echo ::set-output name=EXTENSION::tar.gz
   fi

   _ls "${bin_path}"
   _ls "${TAR_DIR}"

}

_ls() {
   echoerr "contents from $@:"
   ls -la "$@" || true
}

workflow() {

   WORKFLOW_DIR="${NAVI_HOME}/target/workflow"

   cd "$NAVI_HOME"

   rm -rf "${NAVI_HOME}/target" 2> /dev/null || true

   mkdir -p "$WORKFLOW_DIR" 2> /dev/null || true

   cp ${NAVI_HOME}/alfred/* "$WORKFLOW_DIR"
   cd "$WORKFLOW_DIR"
   zip -j -r navi.zip *

}

cmd="$1"
shift

case "$cmd" in
   "release") release "$@" ;;
   "workflow") workflow "$@" ;;
esac
