#!/usr/bin/env bash
set -euo pipefail

docker run \
  -it \
  --entrypoint /bin/bash \
  -v "$(pwd):/navi" \
  ellerbrock/alpine-bash-git \
  -c 'git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && yes | ~/.fzf/install; export PATH=$PATH:/navi; bash'
