#!/usr/bin/env bash
set -euo pipefail

# please refer to https://github.com/denisidoro/dotfiles/blob/master/scripts/code/beautify

export SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

files_to_lint() {
   find . -iname '*.sh'
   find scripts/*
   find shell/*
   echo "${SCRIPT_DIR}/test/run"
   echo "${SCRIPT_DIR}/navi"
}

for f in $(files_to_lint); do
   dot code beautify "$f"
done
