#!/usr/bin/env bash
set -euo pipefail

# please refer to https://github.com/denisidoro/dotfiles/blob/master/scripts/code/beautify

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"

files_to_lint() {
   find . -iname '*.sh'
   find scripts/*
   echo "${NAVI_HOME}/test/run"
   echo "${NAVI_HOME}/navi"
}

for f in $(files_to_lint); do
   dot code beautify "$f"
done
