#!/usr/bin/env bash
set -euo pipefail

##? make install
##? make uninstall

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${NAVI_HOME}/scripts/install"

install() {
   cargo install --path .
}

uninstall() {
   cargo uninstall
}

fix() {
   "${NAVI_HOME}/scripts/fix"
}

cmd="$1"
shift

export X_MODE=true
set -x

case "$cmd" in
   "install") install "$@" ;;
   "uninstall") uninstall "$@" ;;
   "fix") fix "$@" ;;
esac
