#!/usr/bin/env bash
set -euo pipefail

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
TAR_DIR="${NAVI_HOME}/target/tar"

target="${1:-}"

cd "$NAVI_HOME"

rm -rf "${NAVI_HOME}/target" 2> /dev/null || true

if [ -n "$target" ]; then
    cargo install cross 2> /dev/null || true
    cross build --release --locked --target "$target"
    bin_folder="${target}/release"
else 
    cargo build --release --locked
    bin_folder="release"
fi

bin_path="${NAVI_HOME}/target/${bin_folder}/navi"
chmod +x "$bin_path"
mkdir -p "$TAR_DIR" 2> /dev/null || true

cp -r "${NAVI_HOME}/cheats" "$TAR_DIR"
cp -r "${NAVI_HOME}/shell" "$NAVI_HOME"
cp "$bin_path" "$TAR_DIR"

cd "${NAVI_HOME}/target/tar"
tar -czf navi.tar.gz *
