#!/usr/bin/env bash
set -euo pipefail

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${NAVI_HOME}/scripts/install"

version="${1:-$(version_from_toml)}"
log::note "version: $version..."
sleep 2

git tag -a "v${version}"
git push origin --tags
