#!/usr/bin/env bash
set -euo pipefail

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${NAVI_HOME}/scripts/install"

export PATH="/usr/local/Cellar/bash/5.1.8/bin/bash:${PATH}"

"${NAVI_HOME}/tests/run"