#!/usr/bin/env bash
set -euo pipefail

export NAVI_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${NAVI_HOME}/scripts/install"

export PATH="/usr/local/opt/bash/bin/:${PATH}"

"${NAVI_HOME}/tests/run"