#
# Module manifest for module 'navi.plugin'
#
# Generated by: Alexis Opolka (@alexis-opolka)


@{
RootModule = './navi.plugin.psm1'
ModuleVersion = '1.0'
GUID = '59287935-a9b6-4a7f-a1f5-bd6180d9056f'
Author = 'Alexis-Opolka'
CompanyName = 'None'
Copyright = '(c) Alexis Opolka & Navi contributors. All rights reserved.'
FunctionsToExport = @('Invoke-NaviWidget')
CmdletsToExport = @()
VariablesToExport = '*'
AliasesToExport = @()
PrivateData = @{
    PSData = @{
    }
}
### Here should go the HelpInfo XML file if it's supported in
### a later version.
HelpInfoURI = ''
}
